### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by Gunkkk** [LiDongJieHIHA/OPEUDF#2]
It seems that some modules such as "from clientSide.client import OpeClient" are not in the repo. Will they be committed, please?

**Comment by zhoufei0622** [comment]
Hello，How do you set up the environment?，I tried, but didn't get it out，Hope you can help，thanks.

**Comment by Gunkkk** [comment]
> Hello，How do you set up the environment?，I tried, but didn't get it out，Hope you can help，thanks.

@zhoufei0622 Sorry，I have no useful experience for you.

**Comment by zhoufei0622** [comment]
> > Hello，How do you set up the environment?，I tried, but didn't get it out，Hope you can help，thanks.
> 
> @zhoufei0622 Sorry，I have no useful experience for you.

Thanks for your reply,friends
